### ISSUE TITLE
Zmiana ceny co 15 minut

### ISSUE THREAD

**Issue by home409ca** [jacek2511/ha_rce#3]
Planowane jest zagęszczenie danych w atrybutach i pokazanie cen z każdej 15-minutówki?
Wiem, że na razie są takie same.. ale przyszłościowo...?

Ps. Czy integracja pobiera aktualną ceną co godzinę czy co 15 minut a jedynie brakuje tego w atrybutach?

**Comment by jacek2511** [comment]
Jeżeli kiedyś nastąpi zmiana systemu rozliczeń na interwały 15min to oczywiście zostaną one dodane w atrybutach. Integracja ściąga ceny z wszystkich interwałów ale zapisuje tylko te o pełnych godzinach. Dzięki temu baza danych sql nie rozrasta się tak szybko.
Integracja pobiera jednorazowo wszystkie ceny ze strony PSE a potem tylko aktualizowana jest cena w bieżącej godzinie. Dzięki temu nie powinno być opóźnień zmian aktualnej ceny o pełnej godzinie która mogłaby wystąpić podczas zmasowanego odpytywania serwera PSE.
