### ISSUE TITLE
Dodanie atrybutu "Next price"

### ISSUE THREAD

**Issue by home409ca** [jacek2511/ha_rce#6]
Czy możesz dołożyć atrybut "Next price" lub "Trend" (malejący, rosnący)?

Chciałbym wiedzieć, czy następna cena będzie mniejsza, czy większa.

Dzięki

**Comment by jacek2511** [comment]
Dodałem atrybut "Next price" lecz wydaj mi się, że lepiej wykorzystywać atrybut low_price.
